config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'

  get 'mentor' => 'mentor#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :testimonials, only: [:index, :show, :create, :destroy]
  resources :courses, only: [:index, :show]

  resources :students
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :mentor
  has_many :students
  validates :name, presence: true, uniqueness: true
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  has_secure_password

  has_many :courses
  has_many :students, through: :courses

  validates :name, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :github_user, presence: true, uniqueness: true
  belongs_to :course
  has_one :mentor, through: :course
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :user_name, :feedback, presence: true
  before_save :censorship

  private

  def censorship
    if feedback =~ /\bshit\b/
      self.feedback = feedback.downcase.gsub! /\bshit\b/, 'fun'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authorize
    unless Mentor.find_by(id: session[:mentor_id])
      redirect_to login_url, notice: 'Please log in'
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/mentor_controller.rb
class MentorController < ApplicationController

  before_action :authorize

  def index
    @mentor = Mentor.find_by(id: session[:mentor_id])
    @courses = @mentor.courses
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def course
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    mentor = Mentor.find_by(name: params[:name])
    if mentor and mentor.authenticate(params[:password])
      session[:mentor_id] = mentor.id
      redirect_to mentor_url
    else
      redirect_to login_url, alert: 'Invalid username or password'
    end
  end

  def destroy
    session[:mentor_id] = nil
    redirect_to root_url
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authorize, except: [:index, :show]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      flash[:success] = "Student updated"
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to students_url
  end

  private

  def student_params
    params.require(:student).permit(:github_user, :name)
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  respond_to :json

  before_action :authorize, only: :destroy

  def index
    @testimonials = Testimonial.order("id DESC").all
  end

  def show
    @testimonial = Testimonial.find(params[:id])
  end

  def create
    @testimonial = Testimonial.create(testimonial_params)
    respond_with @testimonial
  end

  def destroy
    Testimonial.find(params[:id]).destroy
    redirect_to testimonials_url
  end

  private

  def testimonial_params
    params.require(:testimonial).permit(:user_name, :feedback)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def github_link(student)
    link_to 'GitHub account', "https://github.com/#{student.github_user}",
            target: '_blank', class: 'list-group-item'
  end

  def heroku_link(student)
    link_to 'Heroku application', "https://#{student.heroku_app}.herokuapp.com/",
            target: '_blank', class: 'list-group-item' if student.heroku_app
  end

end

app/views/courses/_course.html.erb
<%= link_to(course.name, course_path(course), class: 'list-group-item') %>

app/views/courses/index.html.erb
<div class="page-header">
  <h1>Courses</h1>
</div>

<div class="list-group">
  <%= render @courses %>
</div>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<p><span class="badge">Students count: <%= @course.students.count %></span></p>
<%= render @course.students%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>

<div class="container text-center">
  <%= yield %>
</div>

</body>
</html>

app/views/mentor/index.html.erb
<div class="page-header">
  <h1>Welcome Admin!</h1>
</div>

<h2>Current courses:</h2>
<div class="list-group">
  <%= render @courses %>
</div>

<h2>Total students count: <%= @mentor.students.count%></h2>

app/views/pages/home.html.erb
<div class="page-header">
    <h1>Hi there</h1>
</div>

<div class="jumbotron">
    <p>This is a demo application for Ruby on Rails course</p>

    <%= link_to 'Visit course page', 'https://github.com/micrum/course',
              target: '_blank', class: 'btn btn-primary btn-lg' %>
</div>

app/views/pages/testimonials.html.erb
<div class="page-header">
    <h1>Testimonials</h1>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <ul class="nav navbar-nav navbar-left">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Courses', courses_path %></li>
    <li><%= link_to 'Testimonials', testimonials_path %></li>
    <li><%= link_to 'Students', students_path %></li>
  </ul>

  <% if session[:mentor_id] %>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Admin', mentor_path %></li>
        <li><%= button_to 'Logout', logout_path, method: :delete, class: 'btn navbar-btn' %></li>
      </ul>
  <% else %>
      <%= link_to 'Login', login_path, class: 'btn btn-default дnavbar-btn pull-right' %>
  <% end %>
</nav>

app/views/students/_form.html.erb
<%= form_for @student, html: {class: 'form-horizontal center'} do |f| %>

    <% if @student.errors.any? %>
        <div class="alert alert-danger">
          <b><%= pluralize(@student.errors.count, "error") %> on form.</b>
          <ul>
            <% @student.errors.full_messages.each do |message| %>
                <li>* <%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :github_user, class: 'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :github_user, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Heroku app name', class: 'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :heroku_app, class: 'form-control' %>
      </div>
    </div>

    <%= f.submit "#{action_name} student", class: 'btn btn-large btn-primary' %>
<% end %>

app/views/students/_student.html.erb
<a href="<%= student_path(student) %>" class="list-group-item">
    <b><%= student.name %></b>
    <p>Github username: <%= student.github_user %></p>
</a>

app/views/students/edit.html.erb
<div class="page-header">
  <h1>Edit student</h1>
</div>

<%= render 'form'%>

app/views/students/index.html.erb
<div class="page-header">
  <h1>Students</h1>
</div>

<% if session[:mentor_id] %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to 'Add new student', new_student_path, class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

<div class="list-group">
  <%= render @students %>
</div>

app/views/students/new.html.erb
<div class="page-header">
  <h1>New student</h1>
</div>

<%= render 'form'%>

app/views/students/show.html.erb
<div class="page-header list-group">
  <h2><%= @student.name %></h2>
  <%= github_link(@student) %>
  <%= heroku_link(@student) %>
</div>

<% if session[:mentor_id] %>
    <%= link_to "edit", edit_student_path(@student), class: 'btn btn-default' %>
    <%= link_to 'delete', @testimonial, method: :delete, class: 'btn btn-danger',
                data: { confirm: "You sure?" } %>
<% end %>

app/views/testimonials/_new_testimonial.html.erb
<div class="modal fade" id="newTestimonialModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

        <%= form_for :testimonial, remote: true, url: testimonials_path,
                     html: {class: 'form-horizontal center testimonial-form'} do |f| %>

            <div class="form-group">
              <%= f.label :user_name, class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.text_field :user_name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :feedback, class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <%= f.text_area :feedback, class: 'form-control' %>
              </div>
            </div>

            <%= f.submit 'Create testimonial', class: 'btn btn-large btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/testimonials/_testimonial.html.erb
<a href="<%= testimonial_path(testimonial) %>" class="list-group-item testimonial">
  <blockquote>
    <p class="testimonial-feedback"><%= testimonial.feedback %></p>
    <footer class="testimonial-footer">
      <%= testimonial.user_name %>
      <span class="testimonial-time"><%= time_ago_in_words(testimonial.created_at) %> ago</span>
    </footer>
  </blockquote>
</a>

app/views/testimonials/index.html.erb
<div class="page-header">
  <h1>Testimonials</h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to 'Add new testimonial', '#', class: 'btn btn-primary btn-lg',
                data: {toggle: 'modal', target: '#newTestimonialModal'} %>
  </div>
</div>

<div class="list-group">
  <%= render @testimonials %>
</div>

<%= render 'new_testimonial'%>

app/views/testimonials/show.html.erb
<div class="page-header">
  <h2><%= @testimonial.user_name %></h2>
  <q><%= @testimonial.feedback %></q>
</div>